# Generated by Django 4.0.4 on 2022-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default='2022-04-16'),
            preserve_default=False,
        ),
    ]
